sudo: required
services:
  - docker

before_install:
  - docker build -t superdba111/docker-react -f Dockerfile.dev .

script:
  - docker run superdba111/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-809677047032"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"



#Docker-env.jy2x7xtmhz.us-east-2.elasticbeanstalk.com